export const FUNNEL_OPTIONS = [
  { value: "upper", emoji: "🔺", label: "Upper Funnel", tag: "Awareness", description: "Pull traffic & build awareness", objective: "Reach out to new customers who don't know your product yet", examples: ["Relatable problem", "Storytelling", "Point of view (POV)", "Trending hook"], color: "blue" },
  { value: "middle", emoji: "🔶", label: "Middle Funnel", tag: "Consideration", description: "Educate & build trust", objective: "Gain video views, community interaction and warm up leads", examples: ["Review / UGC", "Before & after", "Feature highlight", "Product demo"], color: "yellow" },
  { value: "lower", emoji: "🔻", label: "Lower Funnel", tag: "Conversion", description: "Drive purchase & close sales", objective: "Promotion, lead generation and direct purchase intent", examples: ["Limited offer", "CTA to buy", "Testimonial + price", "Urgency / scarcity"], color: "green" },
];

export const FUNNEL_HOOK_MAP = {
  upper: ["question", "bold_claim", "reveal", "before_after"],
  middle: ["problem_agitate", "before_after", "social_proof", "reveal"],
  lower: ["bold_claim", "social_proof", "problem_agitate", "question"],
};

export const FUNNEL_CTA_MAP = {
  upper: ["follow", "save_post", "comment"],
  middle: ["comment", "save_post", "follow", "shop_link"],
  lower: ["shop_link", "try_it", "comment"],
};

export const OPTS = {
  platform: [
    { value: "tiktok", label: "TikTok (9:16)" },
    { value: "reels", label: "Instagram Reels (9:16)" },
    { value: "youtube_shorts", label: "YouTube Shorts (9:16)" },
    { value: "feed_square", label: "Feed Post (1:1)" },
  ],
  grokPlan: [
    { value: "free", label: "🆓 Grok Free (6s per clip)" },
    { value: "pro", label: "⭐ Grok Pro (10s per clip)" },
  ],
  videoStyle: [
    { value: "ugc", label: "UGC — authentic, shot-on-phone" },
    { value: "commercial", label: "Commercial — polished, studio-lite" },
    { value: "lifestyle", label: "Lifestyle — candid, everyday" },
    { value: "tutorial", label: "Tutorial / How-to" },
    { value: "testimonial", label: "Testimonial — talking to camera" },
    { value: "unboxing", label: "Unboxing — reveal & first impression" },
  ],
  tone: [
    { value: "calm_warm", label: "Calm & warm" },
    { value: "energetic", label: "Energetic & upbeat" },
    { value: "trustworthy", label: "Trustworthy & informative" },
    { value: "fun_playful", label: "Fun & playful" },
    { value: "premium", label: "Premium & aspirational" },
    { value: "relatable", label: "Relatable & everyday" },
  ],
  settingPreset: [
    { value: "", label: "— Select preset —" },
    { value: "home_kitchen", label: "Home — kitchen" },
    { value: "home_living", label: "Home — living room" },
    { value: "home_bedroom", label: "Home — bedroom" },
    { value: "home_outdoor", label: "Home — outdoor / garden" },
    { value: "cafe", label: "Café / coffee shop" },
    { value: "office", label: "Office / workspace" },
    { value: "outdoor_urban", label: "Outdoor — urban street" },
    { value: "outdoor_nature", label: "Outdoor — nature / park" },
    { value: "gym", label: "Gym / fitness space" },
    { value: "studio_neutral", label: "Studio — neutral background" },
    { value: "custom", label: "✏️ Custom (type below)" },
  ],
  lightingPreset: [
    { value: "", label: "— Select preset —" },
    { value: "natural_day", label: "Natural daylight (bright, airy)" },
    { value: "golden_hour", label: "Golden hour / warm afternoon" },
    { value: "indoor_warm", label: "Indoor warm artificial light" },
    { value: "indoor_cool", label: "Indoor cool / neutral light" },
    { value: "studio_soft", label: "Studio soft box (clean, even)" },
    { value: "moody_low", label: "Moody low light (dramatic)" },
    { value: "custom", label: "✏️ Custom (type below)" },
  ],
  talent: [
    { value: "solo_female", label: "Solo female (25–35)" },
    { value: "solo_male", label: "Solo male (25–35)" },
    { value: "solo_female_mature", label: "Solo female (40–55)" },
    { value: "solo_male_mature", label: "Solo male (40–55)" },
    { value: "couple", label: "Couple" },
    { value: "group_friends", label: "Group of friends" },
    { value: "family", label: "Family (adult + child)" },
    { value: "no_talent", label: "No talent — product only" },
  ],
  talentStyle: [
    { value: "casual", label: "Casual" },
    { value: "smart_casual", label: "Smart casual" },
    { value: "modest", label: "Modest / conservative" },
    { value: "sporty", label: "Sporty / activewear" },
    { value: "professional", label: "Professional" },
    { value: "cultural", label: "Cultural / traditional" },
  ],
  cameraMove: [
    { value: "static", label: "Mostly static" },
    { value: "gentle_handheld", label: "Gentle handheld" },
    { value: "slow_push_in", label: "Slow push-in" },
    { value: "pan_follow", label: "Pan / follow subject" },
    { value: "mixed", label: "Mixed" },
  ],
  heroAngle: [
    { value: "", label: "— Select —" },
    { value: "45_elevated", label: "45° elevated (recommended)" },
    { value: "eye_level", label: "Eye-level straight-on" },
    { value: "top_down", label: "Top-down / flat-lay" },
    { value: "low_angle", label: "Low angle (prestige)" },
    { value: "close_up_detail", label: "Close-up on key detail" },
  ],
  hooks: [
    { value: "question", label: "Open with a question" },
    { value: "bold_claim", label: "Bold claim / statement" },
    { value: "problem_agitate", label: "Problem → agitate → solve" },
    { value: "reveal", label: "Unexpected reveal" },
    { value: "social_proof", label: "Social proof opener" },
    { value: "before_after", label: "Before & after contrast" },
  ],
  cta: [
    { value: "shop_link", label: "Shop via link in bio" },
    { value: "comment", label: "Comment for more info" },
    { value: "follow", label: "Follow for more" },
    { value: "save_post", label: "Save this post" },
    { value: "try_it", label: "Try it yourself" },
    { value: "no_cta", label: "No explicit CTA" },
  ],
  voLang: [
    { value: "", label: "— Select —" },
    { value: "english", label: "English" },
    { value: "bm", label: "Bahasa Malaysia" },
    { value: "mandarin", label: "Mandarin" },
    { value: "tamil", label: "Tamil" },
    { value: "codemix_bm_en", label: "BM + English (code-switch)" },
    { value: "none", label: "No voiceover (visual only)" },
  ],
  restrictions: [
    { value: "no_text_overlay", label: "No text overlay" },
    { value: "no_effects", label: "No artificial effects" },
    { value: "no_music", label: "No background music" },
    { value: "no_exaggerated_acting", label: "No exaggerated acting" },
    { value: "no_influencer_vibe", label: "No influencer vibe" },
    { value: "no_branded_bg", label: "No branded items in BG" },
    { value: "no_children", label: "No children in frame" },
    { value: "halal_visual", label: "Visually halal-compliant" },
    { value: "no_male_talent", label: "No male talent" },
    { value: "no_competitor", label: "No competitor products" },
  ],
};
