// longvideo-api.js
// Single serverless function for all Long Video operations
// action: 'storylines' | 'prompts' | 'clip1' | 'extend'

import { fal } from "@fal-ai/client";
fal.config({ credentials: process.env.FAL_API_KEY });

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { action } = req.body;
  if (!action) return res.status(400).json({ error: "action is required" });

  if (action === "storylines") return handleStorylines(req, res);
  if (action === "prompts")    return handlePrompts(req, res);
  if (action === "clip1")      return handleClip1(req, res);
  if (action === "extend")     return handleExtend(req, res);

  return res.status(400).json({ error: `Unknown action: ${action}` });
}

// ── ACTION: Generate 5 storylines ────────────────────────────────────────────

async function handleStorylines(req, res) {
  try {
    const {
      productDescription,
      productUSP,
      funnel,
      shape,
      dimensions,
      productImage,
      lang,
    } = req.body;

    if (!productDescription) return res.status(400).json({ error: "productDescription is required" });

    const funnelGuide = {
      upper:  "AWARENESS — hook with a relatable problem, no hard sell, make viewer curious",
      middle: "CONSIDERATION — show product solving a real problem, build trust and credibility",
      lower:  "CONVERSION — create urgency, strong desire, clear reason to buy NOW",
    }[funnel] || "GENERAL — showcase product attractively with a clear benefit";

    const dimParts = [];
    if (dimensions?.height) dimParts.push(`${dimensions.height}cm tall`);
    if (dimensions?.width)  dimParts.push(`${dimensions.width}cm wide`);
    if (dimensions?.depth)  dimParts.push(`${dimensions.depth}cm deep`);
    const shapeContext = shape
      ? `PRODUCT SHAPE & SIZE: ${shape}${dimParts.length ? ` — approximately ${dimParts.join(", ")}` : ""} — ensure the host holds and interacts with the product in a physically realistic way.`
      : "";

    const langInstruction = lang === "zh"
      ? "\n\nIMPORTANT: Generate ALL text fields in Simplified Chinese (简体中文)."
      : lang === "bm"
      ? "\n\nIMPORTANT: Generate ALL text fields in Bahasa Malaysia."
      : "";

    const systemInstruction = `You are a senior social media content producer specialising in 18-second host-driven product marketing videos for TikTok and Instagram Reels.

HOST-CENTRIC FRAMEWORK (non-negotiable):
- ONE consistent host carries the entire 18-second video
- The host holds and physically interacts with the product in Acts 1 and 2
- The same scene/location is maintained throughout — no jump cuts to different locations

CRITICAL PRODUCT VISIBILITY RULE:
- The product reference image is only used in Act 1 (clip 1 generation)
- Acts 2 and 3 are generated by AI video extension — they inherit visual continuity from Act 1
- Therefore: the story MUST keep the product visible in Acts 1 AND 2 (host holds/interacts with it)
- For Act 3 (CTA): host can set product down, gesture toward it, or continue holding it
- NEVER design a story where the product disappears after Act 1

Story arc: Hook (Act 1, 0-6s) → Content/Demo (Act 2, 6-12s) → CTA (Act 3, 12-18s)

Return ONLY valid JSON. No explanation. No markdown.${langInstruction}`;

    const userPrompt = `Propose 5 completely different 18-second host-driven product video storylines.

PRODUCT: ${productDescription}
${productUSP ? `USP: ${productUSP}` : ""}
${shapeContext}
OBJECTIVE: ${funnelGuide}
DURATION: 18 seconds = Act 1 Hook (0-6s) + Act 2 Content (6-12s) + Act 3 CTA (12-18s)

RULES:
- Each storyline must have a completely different emotional hook and energy
- Each must feel like a different type of ad: lifestyle, demo, testimonial, cinematic, UGC
- Host appearance (gender, age range, look, energy) — choose based on product and funnel fit
- Host must physically hold and interact with the product in Acts 1 and 2
- Product stays in frame throughout Acts 1 and 2
- Act 3: host delivers strong CTA — product remains visible or clearly placed on a surface

Return exactly this JSON:
{
  "storylines": [
    {
      "id": 1,
      "title": "3-5 word catchy title",
      "hook": "What happens in Act 1 (0-6s): host appearance, opening action, product introduction",
      "content": "What happens in Act 2 (6-12s): product demo or feature shown by host while holding it",
      "cta": "What happens in Act 3 (12-18s): host CTA delivery, closing shot — product still visible",
      "host": "Brief host description: gender, age range, look/energy that suits this product and funnel",
      "scene": "Location/environment for the whole video — consistent across all 3 acts",
      "emotion": "Primary emotion targeted",
      "style": "e.g. UGC, cinematic, lifestyle, testimonial"
    }
  ]
}`;

    const parts = [];
    if (productImage?.data) {
      parts.push({ inline_data: { mime_type: productImage.mimeType || "image/jpeg", data: productImage.data } });
      parts.push({ text: "This is the product reference image. Use it to understand the product's appearance, colour, and real-world size so host interactions are physically realistic." });
    }
    parts.push({ text: userPrompt });

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GOOGLE_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: systemInstruction }] },
          contents: [{ role: "user", parts }],
          generationConfig: { temperature: 1.2, topP: 0.97, maxOutputTokens: 2000 },
        }),
      }
    );
    const data = await response.json();
    if (!response.ok) return res.status(response.status).json({ error: "Storyline generation failed", details: data });

    const raw = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";
    if (!raw) return res.status(500).json({ error: "Empty response from Gemini" });

    let parsed;
    try { parsed = JSON.parse(raw.replace(/```json|```/g, "").trim()); }
    catch (e) { return res.status(500).json({ error: "Failed to parse storylines", raw }); }

    console.log(`[longvideo-api:storylines] funnel=${funnel} stories=${parsed.storylines?.length}`);
    return res.status(200).json(parsed);

  } catch (error) {
    console.error("[longvideo-api:storylines] Exception:", error.message);
    return res.status(500).json({ error: "Storyline generation failed", details: error.message });
  }
}

// ── ACTION: Generate 3-part prompts ──────────────────────────────────────────

async function handlePrompts(req, res) {
  try {
    const { storyline, productDescription, productUSP, funnel, videoRatio, shape, dimensions, lang } = req.body;

    if (!storyline || !productDescription) return res.status(400).json({ error: "storyline and productDescription are required" });

    const ratioLabel = videoRatio === "16:9" ? "16:9 landscape" : videoRatio === "1:1" ? "1:1 square" : "9:16 vertical portrait";
    const funnelGuide = {
      upper:  "AWARENESS — relatable hook, no hard sell, soft CTA",
      middle: "CONSIDERATION — demonstrate solving a real problem, build trust",
      lower:  "CONVERSION — create urgency, desire, clear buy CTA",
    }[funnel] || "GENERAL — showcase product attractively";

    const dimParts = [];
    if (dimensions?.height) dimParts.push(`${dimensions.height}cm tall`);
    if (dimensions?.width)  dimParts.push(`${dimensions.width}cm wide`);
    if (dimensions?.depth)  dimParts.push(`${dimensions.depth}cm deep`);
    const shapeContext = shape
      ? `Product shape: ${shape}${dimParts.length ? `, approximately ${dimParts.join(" × ")}` : ""}. Ensure host grip and interactions are physically realistic.`
      : "";

    const langInstruction = lang === "zh"
      ? "\n\nIMPORTANT: Write ALL three prompts entirely in Simplified Chinese (简体中文)."
      : lang === "bm"
      ? "\n\nIMPORTANT: Write ALL three prompts entirely in Bahasa Malaysia."
      : "";

    const systemInstruction = `You are an expert Grok AI video prompt engineer specialising in 18-second chained product marketing videos powered by xAI's Aurora engine.${langInstruction}

HOW THE 3-CLIP CHAIN WORKS:
- Clip 1 (reference-to-video, 6s): Grok generates from scratch using @Image1 as product reference. Needs a COMPLETE brief covering all visual layers.
- Clip 2 (extend-video, 6s): Grok INHERITS the full scene, host, lighting, and style from Clip 1. Only the new host action is needed.
- Clip 3 (extend-video, 6s): Same — Grok inherits everything. Only the CTA action is needed.

PROMPT 1 FRAMEWORK — follow this order in one flowing paragraph (80–150 words):
[Host + Opening Action] → [Location/Scene] → [Camera Move] → [Lighting] → [Audio] → [Stability Note] → [Negative Constraints]

PROMPT 1 NON-NEGOTIABLE RULES:
1. FRONT-LOAD: First sentence = host description + primary action. Grok weights the opening most heavily.
2. REFERENCE USAGE: @Image1 is the product. Do NOT re-describe it in full — focus on what to ANIMATE (what the host does with it) and what to PRESERVE (exact shape, proportions, colour).
3. PRECISE LANGUAGE: No vague words like "cinematic" or "dynamic" — be specific: "soft top-light with warm rim", "handheld follow at chest height", "upbeat lo-fi beat with light product tap sound".
4. AUDIO IS REQUIRED: Grok generates native audio. Specify music genre/mood + at least one ambient sound.
5. STABILITY NOTE: Penultimate sentence must lock in: "Keep the host's face, outfit and @Image1 appearance consistent throughout."
6. NEGATIVE CONSTRAINTS (always last): "No text overlays, no scene cuts, no warped hands or faces, product maintains exact size and proportions."

PROMPTS 2 & 3 RULES (extend-video — strict):
- 20–40 words MAXIMUM. One sentence preferred, two sentences at most.
- Start with "Continue the scene:" — this signals video extension to Grok.
- Describe ONLY the new host action and any product movement.
- DO NOT repeat scene, lighting, camera setup, or host appearance — Grok already knows all of this.
- For Prompt 3: include a clear CTA gesture (e.g. "points to camera", "holds product up with a confident nod").`;

    const userPrompt = `Write 3 Grok video prompts for this 18-second product marketing chain.

PRODUCT: ${productDescription}
${productUSP ? `USP: ${productUSP}` : ""}
${shapeContext}
FUNNEL: ${funnelGuide}
RATIO: ${ratioLabel}
HOST: ${storyline.host || "Gemini should decide based on product and funnel"}
SCENE: ${storyline.scene || "Clean, product-appropriate environment"}

CONFIRMED STORYLINE:
Act 1 — Hook (0-6s): ${storyline.hook}
Act 2 — Content (6-12s): ${storyline.content}
Act 3 — CTA (12-18s): ${storyline.cta}
Emotion: ${storyline.emotion}
Style: ${storyline.style}

---

PROMPT 1 — reference-to-video (6s Hook), 80–150 words, one paragraph:
Order: Host+Action → Scene → Camera → Lighting → Audio → Stability Note → Negative Constraints
Use @Image1 for the product. Show what the host DOES with it, not what it looks like.

PROMPT 2 — extend-video (6s Content), 20–40 words:
"Continue the scene:" + host action for Act 2 only. Nothing else.

PROMPT 3 — extend-video (6s CTA), 20–40 words:
"Continue the scene:" + host CTA action + clear call-to-action gesture. Nothing else.

Return exactly this JSON (no markdown, no extra keys):
{
  "prompt1": "...",
  "prompt2": "...",
  "prompt3": "..."
}`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GOOGLE_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: systemInstruction }] },
          contents: [{ role: "user", parts: [{ text: userPrompt }] }],
          generationConfig: { temperature: 0.9, topP: 0.95, maxOutputTokens: 600 },
        }),
      }
    );
    const data = await response.json();
    if (!response.ok) return res.status(response.status).json({ error: "Prompt generation failed", details: data });

    const raw = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";
    if (!raw) return res.status(500).json({ error: "Empty response from Gemini" });

    let parsed;
    try { parsed = JSON.parse(raw.replace(/```json|```/g, "").trim()); }
    catch (e) { return res.status(500).json({ error: "Failed to parse prompts", raw }); }

    if (!parsed.prompt1 || !parsed.prompt2 || !parsed.prompt3) return res.status(500).json({ error: "Incomplete prompts returned", raw });

    console.log(`[longvideo-api:prompts] funnel=${funnel} ratio=${videoRatio} title="${storyline.title}"`);
    return res.status(200).json(parsed);

  } catch (error) {
    console.error("[longvideo-api:prompts] Exception:", error.message);
    return res.status(500).json({ error: "Prompt generation failed", details: error.message });
  }
}

// ── ACTION: Generate Clip 1 (reference-to-video, 6s) ─────────────────────────

async function handleClip1(req, res) {
  try {
    const { prompt, videoRatio, productImageBase64, productImageMime } = req.body;

    if (!prompt) return res.status(400).json({ error: "prompt is required" });
    if (!productImageBase64) return res.status(400).json({ error: "productImageBase64 is required" });

    const imageBlob = base64ToBlob(productImageBase64, productImageMime || "image/jpeg");
    const imageUrl = await fal.storage.upload(imageBlob);
    console.log(`[longvideo-api:clip1] Uploaded product image: ${imageUrl}`);

    const modelId = "xai/grok-imagine-video/reference-to-video";
    const input = {
      prompt,
      reference_image_urls: [imageUrl],
      aspect_ratio: videoRatio || "9:16",
      duration: 6,
      resolution: "720p",
    };

    const webhookUrl = `https://${req.headers.host}/api/grok-webhook`;
    const { request_id } = await fal.queue.submit(modelId, { input, webhookUrl });

    console.log(`[longvideo-api:clip1] Submitted. request_id=${request_id}`);
    return res.status(200).json({ requestId: request_id, modelId, status: "IN_QUEUE" });

  } catch (error) {
    console.error("[longvideo-api:clip1] Error:", error.message);
    return res.status(500).json({ error: error.message || "Clip 1 generation failed" });
  }
}

// ── ACTION: Extend clip (extend-video) ───────────────────────────────────────

async function handleExtend(req, res) {
  try {
    const { videoUrl, prompt, clipNumber } = req.body;

    if (!videoUrl) return res.status(400).json({ error: "videoUrl is required" });
    if (!prompt)   return res.status(400).json({ error: "prompt is required" });

    const modelId = "xai/grok-imagine-video/extend-video";
    const input = { video_url: videoUrl, prompt, duration: 6 };

    const webhookUrl = `https://${req.headers.host}/api/grok-webhook`;
    const { request_id } = await fal.queue.submit(modelId, { input, webhookUrl });

    console.log(`[longvideo-api:extend] clip${clipNumber || "?"} request_id=${request_id}`);
    return res.status(200).json({ requestId: request_id, modelId, status: "IN_QUEUE" });

  } catch (error) {
    console.error("[longvideo-api:extend] Error:", error.message);
    return res.status(500).json({ error: error.message || "Video extension failed" });
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function base64ToBlob(base64, mimeType) {
  const byteCharacters = atob(base64);
  const byteArrays = [];
  for (let offset = 0; offset < byteCharacters.length; offset += 512) {
    const slice = byteCharacters.slice(offset, offset + 512);
    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) byteNumbers[i] = slice.charCodeAt(i);
    byteArrays.push(new Uint8Array(byteNumbers));
  }
  return new Blob(byteArrays, { type: mimeType });
}
